name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out a bug report.
        Please keep reports focused to a single issue and provide all the requested details.
  - type: textarea
    id: elpaca-version
    attributes:
      label: Elpaca Version
      description: Output of the elpaca-version command
      placeholder: M-x elpaca-version
    validations:
      required: true
  - type: textarea
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system are you using Emacs on?
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Describe the problem, what you expected to happen, and what actually happened. Please include steps to reproduce the bug if possible. If the bug involves a package recipe, please include that recipe.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: emacs-lisp
