name: Support
description: Ask a question about using Elpaca
title: "[Support]: "
labels: ["support"]
body:
  - type: markdown
    attributes:
      value: Please keep issues focused to a single topic and provide all the requested details.
  - type: textarea
    id: elpaca-version
    attributes:
      label: Elpaca Version
      description: Output of the elpaca-version command
      placeholder: M-x elpaca-version
    validations:
      required: true
  - type: textarea
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system are you using Emacs on?
    validations:
      required: true
  - type: textarea
    id: question
    attributes:
      label: question
      description: Your question
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant information
      description: If applicable, please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: emacs-lisp
  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      description: Please ensure you have checked the current documentation (including command/function docstrings) to see if it answers your question.
      options:
        - label: I've read the documentation and I still am unsure.
          required: true
